### ISSUE TITLE
Will it support armv7/armv7s?

### ISSUE THREAD

**Issue by alexlee002** [belozierov/SwiftCoroutine#18]
I found no code about armv7 or armv7s in the file CCoroutine.c, will it support this arch?

**Comment by belozierov** [comment]
@alexlee002 Hi, unfortunately it doesn't support 32-bit architectures and I don't plan to add this support.

The last supporting armv7 architecture is iPhone 5 with iOS 10 support. That's why maybe it would be better to set the minimal required version to iOS 11, but on the other hand App Store requires 64-bit applications. So actually there is no possibility to develop for armv7. 

Another reason why I don't want to specify iOS 11, is that I don't want to drop iOS 10 support for iPhone SE as an example.

I'd like to hear your thoughts on this.
