### ISSUE TITLE
Crash using recursion inside a coroutine

### ISSUE THREAD

**Issue by roisg** [belozierov/SwiftCoroutine#22]
Hi, I am experiencing crashes in our code when using intense recursion (lots of recursive calls) inside a coroutine block. I have been able to reproduce it in a test inside the project. This is the code:
``` swift
    func testRecursive() {
        let exp = expectation(description: "testRecursive")
        exp.expectedFulfillmentCount = 1
        DispatchQueue.global().startCoroutine {
            try self.recursiveFunction(count: 0)
            exp.fulfill()
        }
        wait(for: [exp], timeout: 3)
    }
    
    private func recursiveFunction(count: Int) throws {
        let _ = try Coroutine.await { callback in
            DispatchQueue.global().async {
                callback("random_response")
            }
        }
        print(count)
        if count < 10000 {
            try recursiveFunction(count: count + 1)
        }
    }
```

The number of iterations that made the code crash depends on the size of the returned result in the callback function; a more complex object will make the code crash before.

I've tried using `Coroutine.await` as in this sample code, but also using `CoFuture` but it'll always crash eventually. Is it a memory issue? Am I doing something conceptually wrong here?

Thank you!

**Comment by belozierov** [comment]
@roisg Hi. It's not a bug, actually it's a [stack buffer overflow](https://en.wikipedia.org/wiki/Stack_buffer_overflow).

This code will also crash:

```swift
func testRecursive() {
	let exp = expectation(description: "testRecursive")
	exp.expectedFulfillmentCount = 1
	DispatchQueue.global().async {
		try? self.recursiveFunction(count: 0)
		exp.fulfill()
	}
	wait(for: [exp], timeout: 3)
}

private func recursiveFunction(count: Int) throws {
	let _ = DispatchQueue.global().sync {
		"random_response"
	}
	print(count)
	if count < 10000 {
		try recursiveFunction(count: count + 1)
	}
}
```

The problem is that every thread has a stack with a limited size. For example, for background thread on iOS it is 256 kb. And when you call a function recursively, the thread [stack](https://en.wikipedia.org/wiki/Call_stack) fills up with stack frames. And if it reaches its limit, it will crash.
A coroutine also has a stack (I set it to 192 kb). That's why in recursive calls it will also crash, just like a thread when it reaches the limit.

I can only recommend not to use too many recursive calls. Neither inside coroutine nor outside coroutine.

**Comment by roisg** [comment]
Thank you very much, @belozierov! You're absolutely right. This heavily recursive code was inherited by the usage of server-side Vapor's `Futures`, but now that it's possible, it's clear that re-working it to be iterative is the way to go.

**Comment by ckornher** [comment]
Would it be possible/desirable to specify a stack size for specific coroutines?
