### ISSUE TITLE
is it possible to support 32-bit architecture?

### ISSUE THREAD

**Issue by kaelsun** [belozierov/SwiftCoroutine#29]
32-bit architecture support required if we want to use SwiftCoroutine in large projects

**Comment by kaelsun** [comment]
if you don't want to support armv7, could you please explain "how", so i could fork the code and have a try myself...

**Comment by belozierov** [comment]
@kaelsun Hi, in general it is possible, but I refused it for a number of reasons and I am not going to add this support because of complexity to support 64 and 32 bit systems simultaneously.

It is not difficult to add support for the coroutines themselves. You need to add an implementation for armv7 in CCoroutine.c for `__start` func.

The problem is that for CoFuture, CoChannel etc. I use atomic primitives for synchronisations where I everywhere assume they are 64-bit. This is the biggest problem for 32-bit support.

**Comment by kaelsun** [comment]
got it, thanks
